var x = new Date()
console.log(x)
console.log(x.getDay()) //weekDay (0-6)
console.log(x.getDate())
console.log(x.getMonth())
console.log(x.getFullYear())
console.log(x.getHours())
console.log(x.getMinutes())
console.log(x.getSeconds())
console.log("1"-1)